from Locations.Cave import Cave
from Locations.Clearing import Clearing
from Locations.Forest import Forest
from Locations.Forge import Forge
from Locations.House import House
from Locations.Mountain import Mountain
from Locations.Plains import Plains
from Locations.Village import Village
from Locations.Volcano import Volcano
from Locations.WheatField import WheatField
from Locations.BaseLocation import BaseLocation
from Locations.Forest2 import Forest2
